version: '2'
services:
  redis:
    hostname: redis
    image: redis:latest

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/broccoli
    hostname: mws
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - credentials.env
    environment:
      - PYTHONUNBUFFERED=0
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - worker
    links:
      - worker
      - redis
    ports:
      - "5555:5555"

