version: '2'
services:
  redis:
    hostname: redis
    image: redis:latest

  worker:
    build:
      context: worker
      dockerfile: Dockerfile.worker
    volumes:
      - ./worker:/worker
    hostname: mws
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - .env

  web:
    build:
      context: web
      dockerfile: Dockerfile.web
    volumes:
      - ./web:/web
    hostname: web
    depends_on:
      - redis
    links:
      - redis
      - worker
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
      - PORT=5000
    ports:
      - "5000:5000"

  spiders:
    build:
      context: spiders
      dockerfile: Dockerfile.spiders
    volumes:
      - ./spiders:/spiders
    hostname: spiders
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - .env
    ports:
      - "6800:6800"
    command: --help

