version: '2'
services:
  redis:
    hostname: redis
    image: redis:latest

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/broccoli
    hostname: mws
    depends_on:
      - redis
    links:
      - redis
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
    - .:/broccoli
    hostname: web
    depends_on:
      - redis
    links:
      - redis
      - worker
    env_file:
      - .env
    environment:
      - FLASK_DEBUG=1
      - PORT=5000
    ports:
      - "5000:5000"
